/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_freedom_drivers_JBemaFI32 */

#ifndef _Included_org_freedom_drivers_JBemaFI32
#define _Included_org_freedom_drivers_JBemaFI32
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: sMensErroLog */
/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bAlteraSimboloMoeda
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bAlteraSimboloMoeda
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bProgramaAliquota
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bProgramaAliquota
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bProgramaHorarioVerao
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bProgramaHorarioVerao
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNomeiaDepartamento
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bNomeiaDepartamento
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNomeiaTotalizadorNaoSujeitoIcms
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bNomeiaTotalizadorNaoSujeitoIcms
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bProgramaArredondamento
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bProgramaArredondamento
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bProgramaTruncamento
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bProgramaTruncamento
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bLinhasEntreCupons
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bLinhasEntreCupons
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bEspacoEntreLinhas
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bEspacoEntreLinhas
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bForcaImpactoAgulhas
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bForcaImpactoAgulhas
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bAbreCupom
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bAbreCupom
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVendeItem
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVendeItem
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jint, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVendeItemDepartamento
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVendeItemDepartamento
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bCancelaItemAnterior
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bCancelaItemAnterior
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bCancelaItemGenerico
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bCancelaItemGenerico
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bCancelaCupom
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bCancelaCupom
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bFechaCupomResumido
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bFechaCupomResumido
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bFechaCupom
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bFechaCupom
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bResetaImpressora
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bResetaImpressora
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bIniciaFechamentoCupom
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bIniciaFechamentoCupom
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bEfetuaFormaPagamento
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bEfetuaFormaPagamento
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bEfetuaFormaPagamentoDescricaoForma
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bEfetuaFormaPagamentoDescricaoForma
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bTerminaFechamentoCupom
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bTerminaFechamentoCupom
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bEstornoFormasPagamento
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bEstornoFormasPagamento
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bUsaUnidadeMedida
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bUsaUnidadeMedida
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bAumentaDescricaoItem
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bAumentaDescricaoItem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bleiturax
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bleiturax
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bReducaoZ
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bReducaoZ
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRelatorioGerencial
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRelatorioGerencial
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bFechaRelatorioGerencial
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bFechaRelatorioGerencial
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bLeituraMemoriaFiscalData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bLeituraMemoriaFiscalData
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bLeituraMemoriaFiscalReducao
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bLeituraMemoriaFiscalReducao
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bLeituraMemoriaFiscalSerialData
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bLeituraMemoriaFiscalSerialData
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bLeituraMemoriaFiscalSerialReducao
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bLeituraMemoriaFiscalSerialReducao
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRecebimentoNaoFiscal
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRecebimentoNaoFiscal
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bAbreComprovanteNaoFiscalVinculado
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bAbreComprovanteNaoFiscalVinculado
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bUsaComprovanteNaoFiscalVinculadoTef
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bUsaComprovanteNaoFiscalVinculadoTef
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bUsaComprovanteNaoFiscalVinculado
 * Signature: (Ljava/lang/String;)I
 */

JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bUsaComprovanteNaoFiscalVinculado
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bFechaComprovanteNaoFiscalVinculado
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bFechaComprovanteNaoFiscalVinculado
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bSangria
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bSangria
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bSuprimento
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bSuprimento
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNumeroSerie
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bNumeroSerie
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bSubTotal
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bSubTotal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNumeroCupom
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_freedom_drivers_JBemaFI32_bNumeroCupom
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bLeituraXSerial
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bLeituraXSerial
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVersaoFirmware
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVersaoFirmware
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bCGC_IE
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bCGC_1IE
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bGrandeTotal
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_freedom_drivers_JBemaFI32_bGrandeTotal
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bCancelamentos
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_freedom_drivers_JBemaFI32_bCancelamentos
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bDescontos
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_freedom_drivers_JBemaFI32_bDescontos
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNumeroOperacoesNaoFiscais
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bNumeroOperacoesNaoFiscais
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNumeroCuponsCancelados
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_freedom_drivers_JBemaFI32_bNumeroCuponsCancelados
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNumeroIntervencoes
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bNumeroIntervencoes
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNumeroReducoes
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_freedom_drivers_JBemaFI32_bNumeroReducoes
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNumeroSubstituicoesProprietario
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bNumeroSubstituicoesProprietario
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bUltimoItemVendido
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bUltimoItemVendido
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bClicheProprietario
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bClicheProprietario
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNumeroCaixa
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bNumeroCaixa
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bNumeroLoja
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bNumeroLoja
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bSimboloMoeda
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bSimboloMoeda
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bMinutosLigada
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bMinutosLigada
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bMinutosImprimindo
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bMinutosImprimindo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaModoOperacao
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaModoOperacao
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaEpromConectada
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaEpromConectada
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bFlagsFiscais
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bFlagsFiscais
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bValorPagoUltimoCupom
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bValorPagoUltimoCupom
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bDataHoraImpressora
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bDataHoraImpressora
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bContadoresTotalizadoresNaoFiscais
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bContadoresTotalizadoresNaoFiscais
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaTotalizadoresNaoFiscais
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaTotalizadoresNaoFiscais
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bDataHoraReducao
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bDataHoraReducao
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bDataMovimento
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bDataMovimento
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaTruncamento
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaTruncamento
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bAcrescimos
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bAcrescimos
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bContadorBilhetePassagem
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bContadorBilhetePassagem
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaAliquotasIss
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaAliquotasIss
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaFormasPagamento
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaFormasPagamento
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaRecebimentoNaoFiscal
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaRecebimentoNaoFiscal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaDepartamentos
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaDepartamentos
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaTipoImpressora
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaTipoImpressora
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaTotalizadoresParciais
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaTotalizadoresParciais
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRetornoAliquotas
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_freedom_drivers_JBemaFI32_bRetornoAliquotas
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaEstadoImpressora
 * Signature: ()I
 */
JNIEXPORT jstring JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaEstadoImpressora
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bDadosUltimaReducao
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bDadosUltimaReducao
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bMonitoramentoPapel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bMonitoramentoPapel
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaIndiceAliquotasIss
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaIndiceAliquotasIss
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bValorFormaPagamento
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bValorFormaPagamento
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bValorTotalizadorNaoFiscal
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bValorTotalizadorNaoFiscal
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bAutenticacao
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bAutenticacao
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bProgramaCaracterAutenticacao
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bProgramaCaracterAutenticacao
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bAcionaGaveta
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bAcionaGaveta
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaEstadoGaveta
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaEstadoGaveta
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRAbreCupomRestaurante
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRAbreCupomRestaurante
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRRegistraVenda
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRRegistraVenda
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRCancelaVenda
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRCancelaVenda
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRConferenciaMesa
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRConferenciaMesa
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRAbreConferenciaMesa
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRAbreConferenciaMesa
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRFechaConferenciaMesa
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRFechaConferenciaMesa
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRTransferenciaMesa
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRTransferenciaMesa
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRContaDividida
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRContaDividida
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRFechaCupomContaDividida
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRFechaCupomContaDividida
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRTransferenciaItem
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRTransferenciaItem
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRRelatorioMesasAbertas
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRRelatorioMesasAbertas
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRImprimeCardapio
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRImprimeCardapio
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRRelatorioMesasAbertasSerial
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRRelatorioMesasAbertasSerial
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRCardapioPelaSerial
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRCardapioPelaSerial
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRRegistroVendaSerial
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRRegistroVendaSerial
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRVerificaMemoriaLivre
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRVerificaMemoriaLivre
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRFechaCupomRestaurante
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRFechaCupomRestaurante
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRFechaCupomResumidoRestaurante
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRFechaCupomResumidoRestaurante
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bAbreBilhetePassagem
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bAbreBilhetePassagem
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bProgramaMoedaSingular
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bProgramaMoedaSingular
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bProgramaMoedaPlural
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bProgramaMoedaPlural
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bCancelaImpressaoCheque
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bCancelaImpressaoCheque
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaStatusCheque
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaStatusCheque
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bImprimeCheque
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bImprimeCheque
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bIncluiCidadeFavorecido
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bIncluiCidadeFavorecido
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bImprimeCopiaCheque
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bImprimeCopiaCheque
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bAbrePortaSerial
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bAbrePortaSerial
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRetornoImpressora
 * Signature: ()I
 */
JNIEXPORT jstring JNICALL Java_org_freedom_drivers_JBemaFI32_bRetornoImpressora
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bFechaPortaSerial
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bFechaPortaSerial
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bMapaResumo
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bMapaResumo
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bAberturaDoDia
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bAberturaDoDia
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bFechamentoDoDia
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bFechamentoDoDia
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bImprimeConfiguracoesImpressora
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bImprimeConfiguracoesImpressora
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bImprimeDepartamentos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bImprimeDepartamentos
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRelatorioTipo60Analitico
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRelatorioTipo60Analitico
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bRelatorioTipo60Mestre
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bRelatorioTipo60Mestre
  (JNIEnv *, jobject);

/*
 * Class:     org_freedom_drivers_JBemaFI32
 * Method:    bVerificaImpressoraLigada
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_freedom_drivers_JBemaFI32_bVerificaImpressoraLigada
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
